version: '3.7'

# 컴퓨터들을 말한다 yaml은 띄어쓰기가 중요하다 (부모와 자식을 구분하는거기때문에)
services: 

  # 컴퓨터이름 
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:6000

  my-database:
    image: mongo:5
    ports:
      - 27017:27017
    #                 => 하지만, 네임리졸루션으로 express에서는 접속 됨
  # 컴퓨터이름 
  # my-database:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mongo
  #   ports:
  #     - 27017:27017